JENKINS file updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,41 +1,86 @@
-pipeline{
-    agent any 
-    environment{
-        IMAGE_NAME = "mangale1234/"
-        iMAGE_TAG = "${BUILD_NUMBER}"
-        APP_SERVER = "65.0.108.98"
+pipeline {
+    agent any
+
+    environment {
+        IMAGE_NAME = "satishkahar/frontend-app"
+        IMAGE_TAG  = "${BUILD_NUMBER}"
+        APP_SERVER = "13.49.228.23"
     }
-    stages{
-        stage('Checkout'){
-            {
+
+    stages {
+
+        stage('Checkout') {
+            steps {
+                git branch: 'main',
+                    url: 'https://github.com/satish327/Jenkins-webapp.git'
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
                 sh '''
-                docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG
+                docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+                '''
+            }
+        }
 
+        stage('Docker Login') {
+            steps {
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'DockerCred',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_PASS'
+                    )
+                ]) {
+                    sh '''
+                    echo $DOCKER_PASS | docker login \
+                    -u $DOCKER_USER \
+                    --password-stdin
+                    '''
+                }
             }
         }
-        stage('build'){
-            steps{
-                sh 'npm run build'
+
+        stage('Push Image') {
+            steps {
+                sh '''
+                docker push $IMAGE_NAME:$IMAGE_TAG
+
+                docker tag \
+                $IMAGE_NAME:$IMAGE_TAG \
+                $IMAGE_NAME:latest
+
+                docker push $IMAGE_NAME:latest
+                '''
             }
         }
-        stage('Post Build Actions'){
-            steps{
+
+        stage('Deploy To App Server') {
+            steps {
                 sh """
+                ssh ubuntu@$APP_SERVER '
+                docker pull $IMAGE_NAME:latest
+                docker stop frontend || true
+                docker rm frontend || true
 
-                echo 'Cleaning old files on app server'
-
-                ssh jenkins@${APP_SERVER} 'rm -rf ${DEPLOY_DIR}/*'
-
-                echo 'copying frontend build'
-
-                scp -r dist/* jenkins@${APP_SERVER}:${DEPLOY_DIR}/
-
-                echo 'Restarting nginx'
-
-                ssh jenkins@{APP_SERVER} 'sudo systemctl restart nginx'
-                
+                docker run -d \
+                --name frontend \
+                -p 80:80 \
+                $IMAGE_NAME:latest
+                '
                 """
             }
+        }
+    }
+
+    post {
+        success {
+            echo 'Deployment Successful'
+        }
+
+        failure {
+            echo 'Deployment Failed'
         }
     }
 }
